CS/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Home Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CS/src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS/src/objects/Country_Product__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Country Product</relationshipLabel>
        <relationshipName>Country_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cost per Calendar Month</fullName>
                </value>
                <value>
                    <fullName>ATM Fee in other currencies</fullName>
                </value>
                <value>
                    <fullName>Card Replacement Cost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Country Product</relationshipLabel>
        <relationshipName>Country_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Country Product</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Country Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Country Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CS/src/classes/DisplayProductsController.cls
public class DisplayProductsController {
    
    @AuraEnabled
    public static List<Country_Product__c> loadProducts(Contact contact){
        // retrieve matching product information
        List<Country_Product__c> productList = new List<Country_Product__c>();
        productList = [SELECT Id, Country__c, Product__c, Fee__c, Product_Family__c 
                       FROM Country_Product__c WHERE Product__c =:contact.Product__c AND Country__c =: contact.Home_Country__c];
        return productList;
        
    }
    
}